### ISSUE TITLE
module 'xentropy.dihedrals' has no attribute 'DihedralEntropy'

### ISSUE THREAD

**Issue by camattelaer** [liedllab/X-Entropy#74]
Hi there,

Followed the conda installation for linux. Everything seems fine, but i based my initial try resulted on the provided examples and it throws this error:
```
>>> dih_ent = dihedrals.DihedralEntropy(data=data,verbose=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'xentropy.dihedrals' has no attribute 'DihedralEntropy'
```
I couldn't find any info on how to troubleshoot this. 

Kind regards

Charles-Alexandre

**Comment by camattelaer** [comment]
Apparently, the attribute to use is `dihedralEntropy` (note the first lower case).

However i ran into another error which seems problematic:
```
>>> dih_ent.calculate()
Initializing C++ kernel for kde...
/home/camattelaer/Programs/anaconda3/envs/xEntropy/lib/python3.8/site-packages/xentropy/internal/pre_post_processing.py:59: RuntimeWarning: X-Entropy detected dihedral values that are much larger than pi. Your values are assumed to be in degree. X-Entropy expects dihedrals in radian and will transform the unit of your input. If you do not want this transformation, explicitly specify your input unit with the 'input_unit'-argument
  warnings.warn(warn_msg, RuntimeWarning)
KDE finished.
Traceback (most recent call last):
  File "/home/camattelaer/Programs/anaconda3/envs/xEntropy/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 1565, in squeeze
    squeeze = a.squeeze
AttributeError: 'list' object has no attribute 'squeeze'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/camattelaer/Programs/anaconda3/envs/xEntropy/lib/python3.8/site-packages/xentropy/dihedrals.py", line 128, in calculate
    self.__pdf_x = reshape_arrays_eventually(pdf_xs)
  File "/home/camattelaer/Programs/anaconda3/envs/xEntropy/lib/python3.8/site-packages/xentropy/internal/pre_post_processing.py", line 9, in reshape_arrays_eventually
    out = np.squeeze(some_array)
  File "<__array_function__ internals>", line 200, in squeeze
  File "/home/camattelaer/Programs/anaconda3/envs/xEntropy/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 1567, in squeeze
    return _wrapit(a, 'squeeze', axis=axis)
  File "/home/camattelaer/Programs/anaconda3/envs/xEntropy/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 43, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (558,) + inhomogeneous part.
```
somewhere in the code a `list` object is created where attribute `squeeze` is used, but it can't find that attribute...

**Comment by Clownshift** [comment]
Hi [camattelaer](https://github.com/camattelaer),

Sorry, for the late reply. 
Considering your initial post, I think you did not import the module correctly, but I am not sure.
Can you give us a complete code example? 

Did you check the [tutorial](https://github.com/liedllab/X-Entropy/blob/main/examples/XEntropy-example1-dihedral_entropy.ipynb) for that module? Maybe that helps.

**Comment by Clownshift** [comment]
Considering your second comment. This is definitely a small bug on our side. 
Depending on the shape of the data that the users provide, we internally try to reshape the data.
Apparently, you provided data in an unexpected shape.

Can you tell me what data, you provided in which shape? Otherwise, I am not sure, if we need to provide a comprehensive error message for unexpected data shapes, or if there is an actual bug in the reshaping procedure.

Greetings,
